### PR TITLE
Update types.ts

### LINKED ISSUE #335: Compilation fails with v1.2.0
The typescript doesn't compile with the upgrade of trpc-openapi spec, errors out with:

```
project-name:build: ../../node_modules/@trpc/server/src/error/TRPCError.ts(23,19): error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Error'.
project-name:build: ../../node_modules/@trpc/server/src/core/internals/config.ts(19,10): error TS2304: Cannot find name 'window'.
project-name:build: ../../node_modules/@trpc/server/src/core/internals/config.ts(20,13): error TS2304: Cannot find name 'window'.
```

The Project is having the following dependency versions:
```
"@trpc/client": "^10.25.1",
"@trpc/server": "^10.25.1",
"trpc-openapi": "^1.2.0",
"zod": "^3.20.2",
```

I have confirmed the project works fine with v1.1.2.

### PR DESCRIPTION
**Pull request by aliksend**
Fixes #335

### CODE REVIEW

**Comment by Cheunn-Panaa** [comment]
This PR is a duplicate of https://github.com/jlalmes/trpc-openapi/pull/411

**Comment by aliksend** [comment]
@Cheunn-Panaa unfortenately both aren't merged yet

**Comment by Cheunn-Panaa** [comment]
@aliksend Yep.
Patching it is the way we managed to properly use it for now.
I hope we can get some news in the near future...
